[tools]
node = '24.13.0'
pnpm = '10.8.0'
php = '8.4.6'
python = '3.13.3'
golang = '1.24.2'
rust = '1.88.0'
ruby = '3.4.2'
java = '24.0.0'
flutter = '3.29.2-stable'
awscli = '2.26.1'
azure-cli = '2.83.0'
terraform = '1.11.4'
"npm:@openai/codex" = '0.94.0'
